### ISSUE TITLE
Unable to add integration

### ISSUE THREAD

**Issue by abstacek** [veista/nilan#1] opened 2022-11-22 21:13 UTC
![image](https://user-images.githubusercontent.com/95470159/203421973-dd8b2af5-d93f-4743-9b7a-ca5c96579d53.png)
Unable to add integration. Is it necessary to edit configuration.yaml manually, I just don't know how?

**Comment by veista** [comment] 2022-11-22 23:58
Hi, the issue is now resolved with the latest release.

**Comment by abstacek** [comment] 2022-11-23 05:39
Yes already ok, unsupported device for me unfortunately :(

**Comment by veista** [comment] 2022-11-23 07:26
Which device do you have? If it is cts602 based adding support is rather easy.

**Comment by abstacek** [comment] 2022-11-23 07:29
I have a Combi 302 polar top. Can you please advise how to edit/proceed?

**Comment by abstacek** [comment] 2022-11-23 15:25
Hello, could you please advise me how to add support for the Nilan Combi
302 polar? I'll be happy to pay you for your work, I don't want anything
for free. Thank you very much for your help. Adam

st 23. 11. 2022 v 8:26 odesílatel Taneli Veistinen ***@***.***>
napsal:

**Comment by veista** [comment] 2022-11-23 22:02
Ok so first you need to install the newest version 1.0.3. Then take a picture of the **type plate** of your device and add it here.
Then turn on debug logging of the integration in your configuration.yaml file like:
`logger:
  default: info
  logs:
    custom_components.nilan: debug`

Report the debug string here

If you want to support me, you can donate here https://www.buymeacoffee.com/veista

**Comment by veista** [comment] 2022-11-24 13:47
Thanks, do you have the HMI?

**Comment by abstacek** [comment] 2022-11-24 14:35
Yes I do, do you mind if it's not in english?
![IMG_2442](https://user-images.githubusercontent.com/95470159/203809368-f1cc3938-96c8-493c-aa19-6f3c7da59043.jpg)

**Comment by veista** [comment] 2022-11-24 14:37
Thanks, no this is great. I will add this ASAP.

**Comment by veista** [comment] 2022-11-24 17:55
Hi,

The release is now available for you to test. It is beta releases, so make sure you enable beta releases if you are using HACS.

Please let me know if something is missing or something doesn't work.

**Comment by abstacek** [comment] 2022-11-24 18:14
Hi, it worked :-) Great job. Showing 55 entities.
![nilan1](https://user-images.githubusercontent.com/95470159/203846485-878919c0-5b3a-44e3-8aaf-265257e89e3a.png)

**Comment by veista** [comment] 2022-11-24 19:29
That's great! I added a bit better support for your device on version 1.0.5B. Please let me know how it works!

**Comment by veista** [comment] 2022-11-24 19:30
Also do you have an after-heating element installed on your device?

**Comment by abstacek** [comment] 2022-11-24 19:58
The new version 1.0.5b works. I have the polar version with preheating of the supply air so that the exchanger in the unit does not freeze.

**Comment by veista** [comment] 2022-11-24 20:10
![image](https://user-images.githubusercontent.com/91916713/203857974-863a8d72-5cf7-471b-a5c0-b08ed1b9f472.png)

I mean an accessory, you can see it in the HMI menu.

**Comment by abstacek** [comment] 2022-11-24 20:25
This item is in the menu. I don't know if it is actually installed.
![Uploading 5973DB5D-1D37-4F0D-A029-7A74B435F79C.jpeg…]()

**Comment by abstacek** [comment] 2022-11-24 20:28
![92C95E3D-F1BE-4C04-9B4C-43FB90075C46](https://user-images.githubusercontent.com/95470159/203859431-2e576605-8661-4320-9d8f-1dabfe3bc4ff.jpeg)

**Comment by veista** [comment] 2022-11-24 20:33
Great! Then I will code the support for after heating and you can test it.

**Comment by abstacek** [comment] 2022-11-24 20:35
OK. I will try.

**Comment by veista** [comment] 2022-11-25 08:39
So i released the 1.0.6B last night. If you could go through the hmi settings and cross-check that every value changes where it is supposed to and also that there is no unnecessary entities.

**Comment by abstacek** [comment] 2022-11-25 18:19
Hi, I ran into a problem. HA and nilan integration stops working after about a minute. It's like it stopped communicating via modbus. I tried communicating via node-red and it works. I use USR-TCP232-410S for communication, I don't know where the error could be?

**Comment by veista** [comment] 2022-11-25 18:34
Is there anything in the logs?

**Comment by abstacek** [comment] 2022-11-25 18:58
Yes, for example,:
Updating nilan binary_sensor took longer than the scheduled update interval 0:00:10

**Comment by abstacek** [comment] 2022-11-25 18:59
2022-11-25 19:58:52.381 WARNING (MainThread) [homeassistant.components.number] Updating nilan number took longer than the scheduled update interval 0:00:10
2022-11-25 19:58:52.467 WARNING (MainThread) [homeassistant.components.select] Updating nilan select took longer than the scheduled update interval 0:00:10
2022-11-25 19:58:52.647 WARNING (MainThread) [homeassistant.components.climate] Updating nilan climate took longer than the scheduled update interval 0:00:10

**Comment by abstacek** [comment] 2022-11-25 19:01
Only restarting the home assistant will help.

**Comment by veista** [comment] 2022-11-25 19:05
Did you try if reloading the integration helps? Did this problem arise with the latest release?

**Comment by abstacek** [comment] 2022-11-25 19:09
Yes, reload integration will help. But in few minutes it is unavailable again. In previous versions it did too, but I was constantly doing something in HA and restarting HA so I didn't pay much attention to it.

**Comment by abstacek** [comment] 2022-11-25 19:11
ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.nilan_time fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/config/custom_components/nilan/sensor.py", line 397, in async_update
    self._attr_native_value = await getattr(self._device, self._attribute)()
  File "/config/custom_components/nilan/device.py", line 1807, in get_time
    result.registers[i].to_bytes(2, "little", signed=False),
IndexError: list index out of range

**Comment by veista** [comment] 2022-11-25 19:14
It might be an issue with the bridge then. I'm afraid I can only guess from here, but the error comes from that it does not get a response from the device.

**Comment by abstacek** [comment] 2022-11-25 19:20
Yes, there could be a fault with the bridge. I don't really understand that. I just find it strange that even if HA stops communicating, node-red and modbus communicate. So the bridge is communicating, it's just not communicating with HA.

**Comment by veista** [comment] 2022-11-25 19:33
Please note that with these bridges usually, you can only communicate with one TCP client at a time, especially if you run two programs on the same computer, you will run into issues since the server(bridge) does not know which client to respond to and then they get confused.

**Comment by abstacek** [comment] 2022-11-25 19:35
I'm sorry, I didn't know that.

**Comment by veista** [comment] 2022-11-25 20:25
Yes, try to disconnect all other clients from the bridge so that you only have the HA on that bridge. You need another bridge if you want more devices on the RTU network.

**Comment by abstacek** [comment] 2022-11-25 21:27
I have only the nilan combi 302 connected to the modbus bridge and only HA turned on. But still the same problem.

**Comment by veista** [comment] 2022-11-25 21:34
Ok. Then I guess you can try modifying the scan interval or try disabling entities. If you have vs code addon you can modify them there or via text editor if you have samba share.

**Comment by veista** [comment] 2022-11-25 22:02
You can also turn the debug log on for homeassistant.components.modbus if this brings any new info.

**Comment by abstacek** [comment] 2022-11-25 22:09
I will try to adjust the polling interval. This is my bridge setup. Nilan still mentions the use of a 120ohm resistor in the manual, so I'll try to find that too. It is possible that my bridge is not compatible with nilan.
![B09AB348-9094-445B-9BFD-E685B64C840E](https://user-images.githubusercontent.com/95470159/204059289-1035da66-aeb6-46d5-85f7-bb23d5908558.jpeg)

**Comment by veista** [comment] 2022-11-25 22:46
I'm not sure what the issue is, but i don't think it's the resistor. Did you turn the modbus debugging on in HA?

**Comment by veista** [comment] 2022-11-25 22:51
Can you disable that sync baudrate option and try that?

**Comment by abstacek** [comment] 2022-11-25 22:52
Yes.

2022-11-25 23:17:31.075 INFO (MainThread) [homeassistant.setup] Setup of domain input_text took 0.5 seconds
2022-11-25 23:17:31.076 INFO (MainThread) [homeassistant.setup] Setup of domain input_datetime took 0.5 seconds
2022-11-25 23:17:31.076 INFO (MainThread) [homeassistant.setup] Setup of domain zone took 0.5 seconds
2022-11-25 23:17:31.091 INFO (SyncWorker_4) [homeassistant.components.modbus.modbus] modbus Nilan communication open
2022-11-25 23:17:31.097 INFO (MainThread) [homeassistant.setup] Setting up hardware
2022-11-25 23:17:31.126 INFO (MainThread) [homeassistant.setup] Setup of domain input_select took 0.6 seconds
2022-11-25 23:17:31.133 INFO (MainThread) [homeassistant.setup] Setup of domain input_number took 0.6 seconds
2022-11-25 23:17:31.138 INFO (MainThread) [homeassistant.setup] Setup of domain schedule took 0.6 seconds
2022-11-25 23:17:31.148 INFO (MainThread) [homeassistant.setup] Setup of domain hardware took 0.1 seconds
2022-11-25 23:17:31.153 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.apex
2022-11-25 23:17:31.225 INFO (MainThread) [homeassistant.setup] Setting up hacs
2022-11-25 23:17:31.225 INFO (MainThread) [homeassistant.setup] Setup of domain hacs took 0.0 seconds
2022-11-25 23:17:31.235 INFO (MainThread) [homeassistant.setup] Setting up met
2022-11-25 23:17:31.235 INFO (MainThread) [homeassistant.setup] Setup of domain met took 0.0 seconds
2022-11-25 23:17:31.249 INFO (SyncWorker_2) [homeassistant.loader] Loaded switch from homeassistant.components.switch
2022-11-25 23:17:31.255 INFO (MainThread) [homeassistant.setup] Setup of domain input_button took 0.7 seconds
2022-11-25 23:17:31.256 INFO (MainThread) [custom_components.hacs]

**Comment by abstacek** [comment] 2022-11-25 22:55
Is your modbus integration different from other modbus integrations? Sorry for the questions, but I'm not an expert on this.

**Comment by veista** [comment] 2022-11-25 23:03
No. I use the HA built-in modbus library with pretty much default modbus TCP values. It might be that the bridge you are using is not using modbus TCP but only forwards modbus RTU messages. This would mean that it would need a framer, which the HA modbus library has  but it would mean some more coding. I wish I could test that is this the case.

**Comment by abstacek** [comment] 2022-11-25 23:07
Ah, I confess that I do not understand it at all. I would be happy if it worked, I was glad that you modified your program for the Combi 302 and I did not expect that there would be a problem with the bridge. Will I have to buy a new bridge?

**Comment by abstacek** [comment] 2022-11-25 23:09
I turned off sync baudrate but same problem :(

**Comment by veista** [comment] 2022-11-25 23:13
So yes a quick test. In device.py file whre it says "tcp" replace with "rtuovertcp"

**Comment by abstacek** [comment] 2022-11-25 23:21
2022-11-26 00:19:10.911 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: nilan
![image](https://user-images.githubusercontent.com/95470159/204062704-022d9bb9-8d3f-4f5f-a268-79efe89ebd87.png)
after reboot, initialization is in progress

**Comment by abstacek** [comment] 2022-11-25 23:22
Do you want access to HA and bridge?

**Comment by veista** [comment] 2022-11-25 23:29
No, I don't think that would be of any value. It's what I thought, but had to try. I guess you can try increasing the timeout and other settings at the same section, where the modbus config is and see if something works.

**Comment by abstacek** [comment] 2022-11-25 23:32
Ok, I'll try. Thank you very much for your time. I really appreciate it.

**Comment by veista** [comment] 2022-11-25 23:46
Add "message_wait_milliseconds": 30, line after "delay": "",

**Comment by abstacek** [comment] 2022-11-25 23:54
"delay": "", "message_wait_milliseconds": 30,

correctly?

**Comment by veista** [comment] 2022-11-25 23:58
Newline after delay

**Comment by abstacek** [comment] 2022-11-26 00:05
It communicates for 3 minutes and then nothing.

2022-11-26 01:03:07.714 WARNING (MainThread) [homeassistant.helpers.entity] Update of number.nilan_return_fan_power_at_level_2 is taking over 10 seconds
2022-11-26 01:03:07.715 WARNING (MainThread) [homeassistant.helpers.entity] Update of number.nilan_return_fan_power_at_level_3 is taking over 10 seconds
2022-11-26 01:03:07.716 WARNING (MainThread) [homeassistant.helpers.entity] Update of number.nilan_return_fan_power_at_level_4 is taking over 10 seconds
2022-11-26 01:03:07.716 WARNING (MainThread) [homeassistant.helpers.entity] Update of number.nilan_fan_start_up_delay is taking over 10 seconds
2022-11-26 01:03:07.716 WARNING (MainThread) [homeassistant.helpers.entity] Update of number.nilan_defrost_start_setpoint is taking over 10 seconds
2022-11-26 01:03:07.717 WARNING (MainThread) [homeassistant.helpers.entity] Update of number.nilan_defrost_stop_setpoint is taking over 10 seconds
2022-11-26 01:03:07.718 WARNING (MainThread) [homeassistant.helpers.entity] Update of number.nilan_compressor_stop_time is taking over 10 seconds
2022-11-26 01:03:07.719 WARNING (MainThread) [homeassistant.helpers.entity] Update of number.nilan_low_room_temperature_setpoint is taking over 10 seconds
2022-11-26 01:03:07.719 WARNING (MainThread) [homeassistant.helpers.entity] Update of number.nilan_minimum_supply_air_temperature_in_summer is taking over 10 seconds
2022-11-26 01:03:07.720 WARNING (MainThread) [homeassistant.helpers.entity] Update of number.nilan_maximum_supply_air_temperature_in_summer is taking over 10 seconds
2022-11-26 01:03:07.720 WARNING (MainThread) [homeassistant.helpers.entity] Update of number.nilan_room_temperature_neutral_zone is taking over 10 seconds
2022-11-26 01:03:07.747 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities input_boolean.lenka_doma or it is/they are currently not available
2022-11-26 01:03:07.924 WARNING (MainThread) [homeassistant.helpers.entity] Update of select.nilan_air_filter_alarm_interval is taking over 10 seconds
2022-11-26 01:03:07.925 WARNING (MainThread) [homeassistant.helpers.entity] Update of select.nilan_indoor_air_quality_control is taking over 10 seconds
2022-11-26 01:03:07.926 WARNING (MainThread) [homeassistant.helpers.entity] Update of select.nilan_cooling_mode_ventilation_level is taking over 10 seconds
2022-11-26 01:03:07.926 WARNING (MainThread) [homeassistant.helpers.entity] Update of select.nilan_cooling_setpoint_offset is taking over 10 seconds
2022-11-26 01:03:07.928 WARNING (MainThread) [homeassistant.helpers.entity] Update of select.nilan_low_humidity_ventilation_level is taking over 10 seconds
2022-11-26 01:03:07.928 WARNING (MainThread) [homeassistant.helpers.entity] Update of select.nilan_high_humidity_ventilation_level is taking over 10 seconds
2022-11-26 01:03:07.929 WARNING (MainThread) [homeassistant.helpers.entity] Update of select.nilan_hmi_language is taking over 10 seconds
2022-11-26 01:03:07.929 WARNING (MainThread) [homeassistant.helpers.entity] Update of select.nilan_low_outdoor_temp_ventilation_level is taking over 10 seconds
2022-11-26 01:03:07.929 WARNING (MainThread) [homeassistant.helpers.entity] Update of select.nilan_minimum_ventilation_supply_level is taking over 10 seconds
2022-11-26 01:03:07.930 WARNING (MainThread) [homeassistant.helpers.entity] Update of select.nilan_minimum_ventilation_return_level is taking over 10 seconds
2022-11-26 01:03:07.930 WARNING (MainThread) [homeassistant.helpers.entity] Update of select.nilan_maximum_ventilation_return_level is taking over 10 seconds
2022-11-26 01:03:07.931 WARNING (MainThread) [homeassistant.helpers.entity] Update of select.nilan_defrost_ventilation_level is taking over 10 seconds
2022-11-26 01:03:07.931 WARNING (MainThread) [homeassistant.helpers.entity] Update of select.nilan_reset_alarm is taking over 10 seconds
2022-11-26 01:03:08.334 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.nilan_hvac is taking over 10 seconds
2022-11-26 01:03:12.714 WARNING (MainThread) [homeassistant.components.number] Updating nilan number took longer than the scheduled update interval 0:00:15
2022-11-26 01:03:12.924 WARNING (MainThread) [homeassistant.components.select] Updating nilan select took longer than the scheduled update interval 0:00:15
2022-11-26 01:03:13.334 WARNING (MainThread) [homeassistant.components.climate] Updating nilan climate took longer than the scheduled update interval 0:00:15

**Comment by veista** [comment] 2022-11-26 00:14
Set the timeout delay to 1 there is a typo it is 1000. Thats at least one issue I found in the settings.

**Comment by abstacek** [comment] 2022-11-26 00:25
That's it! :-) It's been working for over 10 minutes without a problem. I believe the timeout was causing the whole problem.

**Comment by veista** [comment] 2022-11-26 00:30
Yes the issue was that your bridge doesnt send a response to some message and it was waiting for 1000seconds for that message instead of rejecting the request after 1s and retrying. It was  1000s is longer than the 10s interval so thats why HA couldn't recover.

**Comment by abstacek** [comment] 2022-11-26 00:36
But I'm glad you figured out the problem and were able to fix it. You implemented the supply heating function as you asked about it?

**Comment by veista** [comment] 2022-11-26 00:40
I added the config settings, yes. So if you can cross check the against the HMI it would be great. So change the value in HMI and look in HA if it changes and reads the same value and vice versa.

**Comment by abstacek** [comment] 2022-11-26 07:43
Hello, would it be possible to add these entities (sensors)?
Set temperature
suction fan speed
exhaust fan speed

**Comment by veista** [comment] 2022-11-26 09:35
They should be there. Some options are nested inside the climate entity.

**Comment by abstacek** [comment] 2022-11-26 10:04
In the climate entity there is a desired temperature, but I can't get only this value from the climate entity.

**Comment by veista** [comment] 2022-11-26 10:13
![Screenshot_20221126_121155_Home Assistant](https://user-images.githubusercontent.com/91916713/204083565-4b11fc23-5dd9-4cf4-897f-612d565d15bc.jpg)

**Comment by veista** [comment] 2022-11-26 10:14
Yours should'nt have the preset. Otherwise the same.

**Comment by abstacek** [comment] 2022-11-26 10:20
I would need to get the temperature here.
![77D90962-EB99-4736-8191-23782DED42B2](https://user-images.githubusercontent.com/95470159/204083816-0f8f44f4-795f-4362-8ab2-1852b22025be.jpeg)

**Comment by veista** [comment] 2022-11-26 10:27
You can extact the info from the entity using template sensors. https://www.home-assistant.io/docs/configuration/templating/

**Comment by veista** [comment] 2022-11-26 10:52
But you are right. Integration is missing current ventilatin level.

**Comment by abstacek** [comment] 2022-11-26 11:15
I would like the current value of the ventilation and at the same time the value of both engines in percentage. When I set supply heating on the HMI, nothing happened, but the supply air temperature disappeared.

**Comment by veista** [comment] 2022-11-26 11:36
Hi, I will add the levels, but you will have to code the latter by your self using template sensors, the info should be available to you.

That is interesting, are you sure you are using the extracted value from the climate entity?

**Comment by abstacek** [comment] 2022-11-26 13:29
I think yes.

**Comment by veista** [comment] 2022-11-26 13:32
Do you have the same issues with the latest release?

**Comment by abstacek** [comment] 2022-11-26 13:48
Yes.
![IMG_3430](https://user-images.githubusercontent.com/95470159/204092114-be8363c8-4131-4813-b366-8128b006fe92.PNG)
![IMG_3432](https://user-images.githubusercontent.com/95470159/204092115-7839490a-77a2-4587-bd05-15c686e90b60.jpg)

**Comment by veista** [comment] 2022-11-26 13:55
Can you take a picture of the climate entity? Can you also reload the integration when you have after heating on? Something doesn't work like it should :/

**Comment by abstacek** [comment] 2022-11-26 15:15
I haven't noticed any changes. Either the HMI just shows it as a feature but it's not actually installed, or I didn't understand the feature what it's supposed to do.
![IMG-0434](https://user-images.githubusercontent.com/95470159/204095957-30708801-2004-45d1-b944-52d9d30e7669.jpg)

**Comment by veista** [comment] 2022-11-26 15:37
Ok, so I had understood the documentation a bit wrong. I will draft a new release and you can determine yourself if it is installed or not.

**Comment by veista** [comment] 2022-11-26 15:56
So I released a new version. Can you check if the After Heating Type changes when you enable/disable the after heating?

**Comment by abstacek** [comment] 2022-11-26 16:10
No change even now. Only after upgrading the new version, the "Supply air temperature" entity is not available.
![unnamed (4)](https://user-images.githubusercontent.com/95470159/204098099-dc10021e-db6a-4ea0-97ca-e926d4ec78c9.jpg)
![unnamed (3)](https://user-images.githubusercontent.com/95470159/204098103-d70571f5-f7d6-4b04-ac23-622f76d39873.jpg)

**Comment by veista** [comment] 2022-11-26 16:14
Yes, as it should. The supply air temperature is in the climate entity and you should extract it using templating if you want to use it some other way. This works as it is supposed to.

I am more interested now in the After Heating Type entity I added to the latest release. Does it change when you enable/disable the after heating element?

**Comment by veista** [comment] 2022-11-26 16:28
Oh no, im sorry your right, I confused the supply and return. I will try to fix it, but yes can you respond to the last request, these are related.

**Comment by abstacek** [comment] 2022-11-26 16:31
After Heating Type entity = No Heater

![unnamed (5)](https://user-images.githubusercontent.com/95470159/204098956-eb589e07-32aa-447b-b33c-627dce278636.jpg)

**Comment by veista** [comment] 2022-11-26 16:32
Heater enabled and disabled?

**Comment by abstacek** [comment] 2022-11-26 16:34
Yes, but the entity still shows disabled.

**Comment by veista** [comment] 2022-11-26 16:36
Yes, ok. So the previous version worked correctly, I just didn't understand that you can manually set it on also from the HMI. I guess this concludes that you don't have the heater. And if you read the manual it works as it is supposed to.

**Comment by abstacek** [comment] 2022-11-26 16:58
Oh, so it's possible that I don't actually have this feature installed :( Is it possible to go back to the previous state where Supply air temperature was working?

**Comment by veista** [comment] 2022-11-26 16:59
I can enable the t7 inlet temperature after heater if ghat works in both states even it is against the manual, but if somebody has issues with it in the future i must revert it. But the real problem is that you are able to manually enable the supplementary heater even you don't have it, atleast this is according to the programming manual.

**Comment by veista** [comment] 2022-11-26 17:02
I can enable the t7 inlet temperature after heater if ghat works in both states even it is against the manual, but if somebody has issues with it in the future i must revert it. But the real problem is that you are able to manually enable the supplementary heater even you don't have it, atleast this is according to the programming manual.

**Comment by veista** [comment] 2022-11-26 17:05
Yes, you can go back by just selecting the version in hacs, but I will revert the changes anyway and delete the last release, it was only debugging anyway.

**Comment by abstacek** [comment] 2022-11-26 17:19
And the T2 value from the temperature sensor seems to be missing.

**Comment by veista** [comment] 2022-11-26 17:30
![image](https://user-images.githubusercontent.com/91916713/204101339-277696f8-6ca0-4c19-af9d-37b88075693d.png)

Yes, my code checked if the after-heating element was installed, but I didn't realize that you could force it on even if it is not installed. So this is why the confusion, I determined the correct sensor by what is installed. At least on my model the T7 temperature shows values, so on the latest 1.0.9B I'm only using the T7 and lets try that, but if it causes issues down the line I will have to revert to the previous logic and you will just have to put the after-heating element to NO in the HMI.

**Comment by veista** [comment] 2022-11-26 18:47
Does the latest release work for you?

**Comment by abstacek** [comment] 2022-11-26 18:53
Yes, it works perfectly. I already have the desired temperature displayed as I wanted. I am still looking for the current value of the fan in percent. I have to reward you for your work which is impeccable.

**Comment by veista** [comment] 2022-11-26 19:01
Thanks, it means a lot. That you will have to do by templating since it is not offered by nilan devices directly. It is not complicated once you get the hang of it.

**Closed** 2022-11-26 19:15 UTC
