### ISSUE TITLE
Idea of enhancement: Soft buttons and display replacement va modbus

### ISSUE THREAD

**Issue by gllmlbrt** [veista/nilan#5] opened 2022-12-01 19:43 UTC
Hi again, 

The actual text displayed on the CTS602 panel is transmitted over modbus at the following input addresses 2002 to 2011:
![image](https://user-images.githubusercontent.com/58825251/205143319-c1b6f0c6-55cc-4fc8-abf3-e6ef4d0bffa5.png)

I had that working just fine over MQTT. So I could read exactly what what printed on the panel at the system, which is in a cabinet. Avoiding having to open the cabinet to verify, and was a good way to check immidate effect of the change of state etc...
So I added it here:
![image](https://user-images.githubusercontent.com/58825251/205144725-6110b4a4-279f-450a-b63a-c79156bdf11d.png)

Now also, key press can be written here at the following holding addresses:
![image](https://user-images.githubusercontent.com/58825251/205142526-5e870bff-79bc-4bfd-a21c-3eeb1871d766.png)
That part I never managed to make work over MQTT.

But if both worked here, we could create buttons in lovelace reproducing exactly the panel and calling for service for modbus writing reproducing exactly the panel on a UI, and also having the whole complete menu available from HA.

That would apply/work for all Nilan presumably...

I could help working on this, but I might need a couple of pointer to have the text sent over the integration, and the method to write keypresses to holding reg.

If you think it is not useful, feel free to close the issue, and I might give it a long shot on my own as a fork.

**Comment by veista** [comment] 2022-12-01 19:57
I can add some experimental entities for the ascii fields.

> That would apply/work for all Nilan presumably...

Unfortunately only models without the touch panel. These registers have been removed after touch screen.

Qmodmaster is a great tool to debug and experiment the button presses. If you get it to work I can add a button entity category at some point.

**Comment by veista** [comment] 2022-12-01 20:02
Can you provide a sample for the ascii and other register values?

**Comment by gllmlbrt** [comment] 2022-12-01 20:21
Well here is it from qmodmaster:
![image](https://user-images.githubusercontent.com/58825251/205150005-b68ba2f9-995b-4cd1-bbf5-23c219f4a162.png)
The display shows only 16 bits, and does not allow me to show all of them due to size, I suspect HA modbus integration could do that ?

But that is binary which should be converted to text... 
Not sure how else to get all of it out. BUt anyways converting what I can see, It matches what is written on the panel.

**Comment by veista** [comment] 2022-12-01 20:29
You can just show dec or hex

**Comment by gllmlbrt** [comment] 2022-12-01 20:37
![image](https://user-images.githubusercontent.com/58825251/205154524-c0bd25be-d9af-4c58-b2ca-32b3eb0ea416.png)

**Comment by gllmlbrt** [comment] 2022-12-01 20:40
![image](https://user-images.githubusercontent.com/58825251/205155053-91b2e5f8-c518-46da-9adf-e099241ef423.png)

**Comment by gllmlbrt** [comment] 2022-12-01 20:55
This is all meant to write "HEAT >1< 22C"

**Comment by veista** [comment] 2022-12-01 22:32
Added a new release.

**Comment by veista** [comment] 2022-12-02 14:53
Does the display sensor work as intended?

**Comment by gllmlbrt** [comment] 2022-12-02 17:41
Hey, yes it works as to display whatever is being transmitted over MB, but unfortunately it is a bit messed up:
![image](https://user-images.githubusercontent.com/58825251/205351414-72a67c4a-b148-46e9-ba3d-921ba027c27c.png)

This is meant to read "AUTO L >1< 22C"
I tried with other texts, it works well, but scrambled as well the same way, so it is a parsing order issue only...
So the A and U are inverted, then the O and T are inverted, and > and 1 as well. 
Then there is this ß which I do not know where it comes from, seems to be an error of Tranlation, or just not something which is meant to be in Ascii... I think it is mean to be a space in this case ...

**Comment by gllmlbrt** [comment] 2022-12-02 17:54
Here I managed to write to holding 2000, up and down to get to:
![image](https://user-images.githubusercontent.com/58825251/205353952-20236f2e-28f6-4eca-839d-c415e7adb594.png)
 Which should read "SHOW ALARMS" which make it clear how the order is scrambled.
Technically there are two lines:
![image](https://user-images.githubusercontent.com/58825251/205354769-9bf07b13-4ba5-4069-b8f8-0042e6d2c727.png)
Here it should read "LANGUAGE" in the first line using all 8 characters, and "ENGLISH " using 7 characters and a space. Best example to show both lines, and the scrambling.
I am not sure what would be best, to keep all in one line, or have it as intended on two separate text, as separate lines, if I want to repriduce what the panel shows...

**Comment by gllmlbrt** [comment] 2022-12-02 17:55
Better have it in two separate sensors/lines, I can always template them into one again if needed on some cards.

**Comment by veista** [comment] 2022-12-02 19:06
Made a new release for you to try. 
Yes was wondering about the byte order from your example and got it the wrong way around. It is funny that it is not ascii as stated in the datasheet, but instead HD44780, Nilan has taken a shortcut here.

1. Do the buttons work by just writing to the register as stated in datasheet?
2. Is there a case that requires 2 or more simultaneous button presses?

**Comment by gllmlbrt** [comment] 2022-12-02 19:18
![image](https://user-images.githubusercontent.com/58825251/205368301-abe4eb23-1433-4864-905e-6bc8bfb71564.png)
![image](https://user-images.githubusercontent.com/58825251/205368397-fca24854-acc8-428e-9d72-711d861dd551.png)

Perfect !

1. Yes. Hex input to the holding red address 2000 just does the action.
Tested up, down, enter and escape just fine. The only issue is that it is impossible with the refresh rate to see when a value is blinking after pressed enter for editing...
2. I can think of only one, stay press DOWN and ENTER for 10 seconds to activate the service menu, not sure if it is possible or needed.

**Comment by veista** [comment] 2022-12-02 19:22
Ok. Adding the buttons may take some time.

You can try to improve the refresh rate by shortening the update interval from const.py . Be warned though, if it is too short you will face issues.

**Comment by veista** [comment] 2022-12-02 20:31
Added buttons for testing.

**Comment by gllmlbrt** [comment] 2022-12-02 21:27
I don't seem to see anywhere any button entity created after several restarts, am I missing something ?

**Comment by veista** [comment] 2022-12-02 21:47
It should come up in control entities with version 1.0.17B

**Comment by veista** [comment] 2022-12-02 22:16
sorry, realised the problem, i forgot to push a file.

**Comment by veista** [comment] 2022-12-02 22:21
New release available.

**Comment by veista** [comment] 2022-12-03 14:45
Actually found the correct Modbus manual for your device https://www.en.nilan.dk/Files/Files/Engelsk/Archive/Software%20instructions/2015-01%20CTS%20602_CTS602_Modbus_protokol_ver100.pdf

**Comment by gllmlbrt** [comment] 2022-12-03 20:11
Thanks !
For the buttons, the on / off work great.
For the up/down, it is strange, looking like if I press once, it goes up or down 2 or three steps... Now I have used it remotely (ot home), so I cannot check what is happening actually on the display at the system. Will check again when home tomorrow. 
BUt anyways, it looks like it is going up and down several steps...

And then the blonking is not at all visible when selecting a value for edit. Even with scan_internal=1.

**Comment by veista** [comment] 2022-12-03 20:33
Hi, Yes, I Guessed that might happen since I cannot control the off delay of the button. The action is repeated if not cleared in 400ms. That would have to be made similar to your MQTT device so you could control the button presses more precisely. I'm just wondering what the purpose of the display emulation is if all functions work as entities?

**Comment by veista** [comment] 2022-12-04 12:51
Also I would assume shotening the scan interval makes the buttons work worse, since it might not have enough time slots to send the button off message. That would also be random then how many times it pushes a button. It would be too much effort and convay away from the rest of the integration, so i will propably not add the buttons to the actual integration.

**Comment by veista** [comment] 2022-12-04 12:53
On another subject, do you still get the invalid address errors?

**Comment by veista** [comment] 2022-12-04 14:36
Realized also that your hardware version has also inverted byte order. Will fix this also.

**Comment by gllmlbrt** [comment] 2022-12-04 15:09
Noted about the buttons, makes sense. It was more a nice to have rather than a need to have for sure. 
Yes, still get the error addres as follows:
```
Logger: homeassistant.components.modbus.modbus
Source: components/modbus/modbus.py:391
Integration: Modbus (documentation, issues)
First occurred: 3 December 2022 at 21:03:40 (14974 occurrences)
Last logged: 16:08:45

Pymodbus: Nilan: Exception Response(132, 4, IllegalAddress)
Pymodbus: Nilan: Exception Response(131, 3, IllegalAddress)
```
does not seem to affect any functionality though...

**Comment by veista** [comment] 2022-12-04 15:25
Hi added a new release, hope that this fixes the buttons - If not I will remove them, but you can always add them back if you like them. Hope the new version also fixes Firmware version on your model and removes - at last - the unsupported entities, so you wouldn't get those errors anymore.

**Comment by veista** [comment] 2022-12-04 16:24
Also, I read that Nilan does updates to the older models, so I would concider doing that in your case.

**Comment by gllmlbrt** [comment] 2022-12-06 17:47
Contacted vendor for the update of my system. Haven't heard back yet. I suggest we close this issue and abandon the button thing. If someday I absolutely need that I can remotely connect with qmodmaster... Thanks for the try !

**Comment by gllmlbrt** [comment] 2022-12-06 17:47
Should I open a separate issue for the illegal address error I get ?

**Comment by veista** [comment] 2022-12-06 17:52
Sure. I'm still trying to figure it out. I cross checked every register I read and still this issue remains. I have to be more thorough. Does the version read correct at least?

**Comment by gllmlbrt** [comment] 2022-12-06 18:09
I am not sure what you mean by that ? The error is about an illigal address
```
Logger: homeassistant.components.modbus.modbus
Source: components/modbus/modbus.py:391
Integration: Modbus (documentation, issues)
First occurred: 3 December 2022 at 21:03:40 (14974 occurrences)
Last logged: 16:08:45

Pymodbus: Nilan: Exception Response(132, 4, IllegalAddress)
Pymodbus: Nilan: Exception Response(131, 3, IllegalAddress)
```

I am not sure what it is searching at those addresses, but acc. to my modbus protocol both 131, and 132 are inexistant addresses at both input and holding.

**Comment by veista** [comment] 2022-12-06 20:38
Yes, indeed. The integration reads or writes to a non-existent address, which my device has, but yours doesn't. Just can't find the mistake in the code.

**Comment by veista** [comment] 2022-12-06 22:04
Hi, could you provide me a picture of your panel from:

![image](https://user-images.githubusercontent.com/91916713/206033185-b60e6eec-f966-4759-8314-d325370a5221.png)

**Comment by veista** [comment] 2022-12-07 00:05
Ok, now finally found the last one. Should be fixed on 1.0.22B.

**Comment by gllmlbrt** [comment] 2022-12-07 11:47
Definitely some improvement, now only the one left as below:
```
Logger: homeassistant.components.modbus.modbus
Source: components/modbus/modbus.py:391
Integration: Modbus (documentation, issues)
First occurred: 07:10:45 (2006 occurrences)
Last logged: 12:45:00

Pymodbus: Nilan: Exception Response(132, 4, IllegalAddress)
```

Image below for the type:
![IMG20221207062004](https://user-images.githubusercontent.com/58825251/206171604-582a20cf-5648-4bed-b1e5-b8bdda806647.jpg)

**Comment by veista** [comment] 2022-12-07 23:59
Thanks for the picture! Added some debugging to get to the bottom of this on 1.0.24B. The problem should show up in logs now.

**Comment by gllmlbrt** [comment] 2022-12-08 06:27
Hi, so the logger you added seems to have had some results:
```
Logger: custom_components.nilan.device
Source: custom_components/nilan/device.py:787
Integration: Nilan (documentation, issues)
First occurred: 06:29:10 (301 occurrences)
Last logged: 07:19:11

Could not read get_control_temperature
```
And still of course: 
```
Logger: homeassistant.components.modbus.modbus
Source: components/modbus/modbus.py:391
Integration: Modbus (documentation, issues)
First occurred: 06:29:10 (301 occurrences)
Last logged: 07:19:11

Pymodbus: Nilan: Exception Response(132, 4, IllegalAddress)
```

**Comment by veista** [comment] 2022-12-08 17:52
Thank You! Never would have guessed that the ModBus Manual has duplicate name entries, there were 3 in total.

**Comment by gllmlbrt** [comment] 2022-12-08 19:55
Great ! Error gone with latest beta.

**Comment by veista** [comment] 2022-12-08 20:12
Thank you so much!

**Closed by veista** 2022-12-08 20:12 UTC
Labels: enhancement, question

**Comment by veista** [comment] 2022-12-22 00:43
https://www.en.nilan.dk/products/accessories/control-panels/cts602-hmi-upgrade-kit
